#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require_relative "../lib/ruby_on_git"

require_relative "../lib/cli"

begin
  Cli.start(ARGV)
rescue RubyOnGit::Eixt1 => _e
  exit 1
rescue RubyOnGit::Error => e
  warn e.message
  exit 1
rescue Errno::EACCES => e
  warn "fatal: #{e.message}"
  exit 1
end
